CIRCUITPY_WIFI_SSID        = "SSID"
CIRCUITPY_WIFI_PASSWORD    = "PASSWORD"
CIRCUITPY_WEB_API_PASSWORD = "PWD"
CIRCUITPY_WEB_API_PORT     = 80

ADAFRUIT_AIO_USERNAME      = "USERNAME"
ADAFRUIT_AIO_KEY           = "AIOKEY"
ADAFRUIT_AIO_FEED_KEY      = "FEEDKEY"

UTC_OFFSET = "-7"
